{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gowtham-reddy1198/gowtham-apps.git
<<<<<<< HEAD
    targetRevision: master
=======
    targetRevision: main
>>>>>>> 9598756fc4e8673a3ffeba3346bdef0e9f440f06
    path: {{ .name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
